<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class BusinessUnitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('business_unit')->insert([
            [
                'bu_id' => '13',
                'dashboard_path' => 'bilarbreeder',
                'name' => 'Bilar Breeder AR',
                'database' => 'bilar_breeder_ar',
                'host' => '127.0.0.1',
                'port' => '3306',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'BILAR BREEDER',
                'business_unit_code' => 'BRDR BIL-AG003',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bu_id' => '50',
                'dashboard_path' => 'gpjagna',
                'name' => 'Gp Jagna AR',
                'database' => 'gp_jagna_ar',
                'host' => '127.0.0.1',
                'port' => '3306',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'GP FARM JAGNA',
                'business_unit_code' => 'GPFARM-AG021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // [
            //     'bu_id' => '43',
            //     'dashboard_path' => 'rizalbreeder',
            //     'name' => 'Rizal Breeder AR',
            //     'database' => 'rizal_breeder_live',
            //     'host' => '172.16.217.11',
            //     'port' => '3306',
            //     'username' => 'RizalBreederLive',
            //     'password' => 'FarMsTeaM',
            //     'business_unit' => 'BILAR RIZAL BREEDER',
            //     'business_unit_code' => 'RIZAL BIL-AG015',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            [
                'bu_id' => '16',
                'dashboard_path' => 'lapsaonbreeder',
                'name' => 'Lapsaon Breeder AR',
                'database' => 'lapsaon_breeder_ar',
                'host' => '127.0.0.1',
                'port' => '3306',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'DIMIAO LAPSAON',
                'business_unit_code' => 'BRDR DIMLAP-AG006',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bu_id' => '14',
                'dashboard_path' => 'hatchery',
                'name' => 'Hatchery AR',
                'database' => 'hatchery_ar',
                'host' => '127.0.0.1',
                'port' => '3306',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'BILAR HATCHERY',
                'business_unit_code' => 'HTCH BIL-AG004',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bu_id' => '11',
                'dashboard_path' => 'cortespiggery',
                'name' => 'Cortes Piggery AR',
                'database' => 'cortes_piggery_ar',
                'host' => '127.0.0.1',
                'port' => '3306',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'PIGGERY CORTES',
                'business_unit_code' => 'PGRY CORT-AG001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bu_id' => '12',
                'dashboard_path' => 'cortespoultry',
                'name' => 'Cortes Poultry AR',
                'database' => 'cortes_poultry_ar',
                'host' => '127.0.0.1',
                'port' => '3306',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'POULTRY CORTES',
                'business_unit_code' => 'LAYER CORT-AG002',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bu_id' => '15',
                'dashboard_path' => 'canhayuponbreeder',
                'name' => 'Canhayupon Breeder AR',
                'database' => 'canhayupon_breeder_ar',
                'host' => '127.0.0.1',
                'port' => '3306',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'DIMIAO CANHAYUPON',
                'business_unit_code' => 'BRDR DIMCAN-AG005',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Ubay businessUnit 
            [
                'bu_id' => '17',
                'dashboard_path' => 'dressingplant',
                'name' => 'Dressing Plant AR',
                'database' => 'dressing_plant_ar',
                'host' => '127.0.0.1',
                'port' => '3308',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'DRESSING PLANT',
                'business_unit_code' => 'DRSP UBAY-AG007',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bu_id' => '18',
                'dashboard_path' => 'rendering',
                'name' => 'Rendering AR',
                'database' => 'rendering_ar',
                'host' => '127.0.0.1',
                'port' => '3308',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'RENDERING',
                'business_unit_code' => 'REND UBAY-AG008',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bu_id' => '19',
                'dashboard_path' => 'feedmill',
                'name' => 'Feedmill AR',
                'database' => 'feedmill_ar',
                'host' => '127.0.0.1',
                'port' => '3308',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'FEEDMILL',
                'business_unit_code' => 'FDML UBAY-AG009',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bu_id' => '20',
                'dashboard_path' => 'growout',
                'name' => 'Growout AR',
                'database' => 'growout_ar',
                'host' => '127.0.0.1',
                'port' => '3308',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'GROWOUT',
                'business_unit_code' => 'GRWT UBAY-AG010',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bu_id' => '21',
                'dashboard_path' => 'demofarm',
                'name' => 'Demo Farm AR',
                'database' => 'demofarm_ar',
                'host' => '127.0.0.1',
                'port' => '3308',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'DEMO FARM',
                'business_unit_code' => 'DMO UBAY-AG011',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bu_id' => '22',
                'dashboard_path' => 'mfimanurefertilizerubay',
                'name' => 'Mfi Manure Fertilizer Ubay AR',
                'database' => 'mfi_manure_fertilizer_ubay_ar',
                'host' => '127.0.0.1',
                'port' => '3308',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'MFI MANURE FERTILIZER UBAY',
                'business_unit_code' => 'FERP UBAY-AG012',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bu_id' => '46',
                'dashboard_path' => 'meatprocessingplant',
                'name' => 'Meat Processing Plant AR',
                'database' => 'meat_processing_plant_ar',
                'host' => '127.0.0.1',
                'port' => '3308',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'MEAT PROCESSING PLANT',
                'business_unit_code' => 'MPP-UBAY-AG017',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bu_id' => '23',
                'dashboard_path' => 'piggeryuntaga',
                'name' => 'Piggery Untaga AR',
                'database' => 'piggery_untaga_ar',
                'host' => '127.0.0.1',
                'port' => '3308',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'PIGGERY UNTAGA',
                'business_unit_code' => 'PGRY ALC-AG013',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bu_id' => '41',
                'dashboard_path' => 'farmersmarket',
                'name' => 'Farmers Market AR',
                'database' => 'farmers_market_ar',
                'host' => '127.0.0.1',
                'port' => '3308',
                'username' => 'root',
                'password' => '',
                'business_unit' => 'FARMERS MARKET',
                'business_unit_code' => 'FARMERS MARKET',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
